import { writeFileSync } from "node:fs";
import { join } from "node:path";

const md = `# Database schema

All datetimes are stored as text in UTC ("YYYY-MM-DD HH:MM:SS" or ISO 8601).
The user's timezone is in the \`config\` table (key \`timezone\`).

## sessions

| Column | Type | Notes |
|---|---|---|
| id | INTEGER | Primary key |
| started_at | TEXT | UTC datetime |
| duration_seconds | INTEGER | NULL when not recorded |
| page_start | INTEGER | NULL when not recorded. Range 1-604 (Madinah Mushaf) |
| page_end | INTEGER | NULL when not recorded. Inclusive |
| surah_start | INTEGER | 1-114 |
| ayah_start | INTEGER | 1-based ayah within \`surah_start\` |
| surah_end | INTEGER | 1-114 |
| ayah_end | INTEGER | 1-based ayah within \`surah_end\` |
| ayah_count | INTEGER | Source of truth for volume read |
| type | TEXT | 'normal' or 'kahf' (Friday Surat Al-Kahf) |
| created_at | TEXT | UTC |

## khatmas

A khatma is one full read-through of the Quran. One row per completion.

| Column | Type | Notes |
|---|---|---|
| id | INTEGER | Primary key |
| completed_at | TEXT | Date the khatma was completed |

## config

Key/value store. Known keys: \`city\`, \`country\`, \`timezone\`, \`language\`,
\`chat_id\`, \`kahf_reminder_last\`, \`weekly_recap_last\`.

| Column | Type | Notes |
|---|---|---|
| key | TEXT | Primary key |
| value | TEXT | |

## prayer_cache

Daily prayer time cache. Mostly transient; not useful for reading-history analysis.

# Conventions

- Group sessions by user-day with \`substr(started_at, 1, 10)\`. Stored datetimes
  are already aligned to the user timezone at insertion time.
- "Streak" = number of consecutive days with at least one session.
- Mushaf used: Madinah, 604 pages.
- Surah names: see the \`get_surahs\` tool. Juz/page mapping: \`get_juz_pages\`.
`;

const resourcesDir = join(import.meta.dirname, "..", "src", "mcp", "resources");
writeFileSync(join(resourcesDir, "schema.md"), md);
writeFileSync(
  join(resourcesDir, "schema-text.ts"),
  "// Generated by scripts/gen-schema.ts. Do not edit by hand.\n" +
    `export const schemaMarkdown = ${JSON.stringify(md)};\n`
);
console.log("Wrote src/mcp/resources/schema.md and schema-text.ts");
